# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 698f185844c2b821c41e596e3394ac26a187cce8a7101718670cfc3da39fd328aefe30c09b5db78d51faa5e7a89c70a4297303e820439dcef26140755dd69813

test:
  secret_key_base: d2b0096bbefd1867c68d4430acbb78633d9deb0ad0d5c26d0aeda1c251d2900348b88514ae5d89129e80735a70e300ea396a836ff415ed3bc823079a528f5160

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
